### ISSUE TITLE
Shallow checkout of pandas repository

### ISSUE THREAD

**Issue by twoertwein** [pandas-dev/pandas-ci#7]
I think that the CI fetches/clones more than necessary: I think you only ever care about the latest commit and in most cases only about the master branch.

The CI does `git fetch --tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/*` (I haven't found where that line is hidden, but the test output contains it). I assume you can add a `--depth=1` to only get the most recent commit from each branch. Or even `git clone --depth=1 --single-branch` to get the most recent commit from master?

The only git clone/fetch command I found in pandas/pandas-ci is this one:
https://github.com/pandas-dev/pandas-ci/blob/72101058e419515740eba82a51d49e4967c59ad2/.travis.yml#L25

**Comment by jreback** [comment]
you can try but we need depth in order to properly get tags

in any event this doesn't take much time

**Comment by twoertwein** [comment]
> you can try but we need depth in order to properly get tags

`git fetch --depth=1 --tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/*` still seems to allows you to checkout a specific tag :)

Do you have a pointer for me where the travis/azur pipelines are defined to better understand how the CI uses git?

> in any event this doesn't take much time

The above fetch command downloads 32.41 MiB while without the depth argument it downloads 189.65 MiB! It might not speed up the CI pipeline by much but it might reduce pandas's infrastucture cost (I assume someone has to pay for that).

**Comment by jreback** [comment]
infrastrue is hosted gratis for both Travis & Azure; happy to reduce usage of course.

> Do you have a pointer for me where the travis/azur pipelines are defined to better understand how the CI uses git?

see .travis.yml and ci/azure/

**Comment by twoertwein** [comment]
I must admit that I expected there to be more or less a simple shell script with all the steps as printed in the test output (including all the git commands).

There are also a [few good reasons](https://stackoverflow.com/questions/31278233/disadvantages-of-shallow-cloning-on-travis-and-other-ci-services) not use `--depth=1` and travis (and probably azure) already have their own syntax to define shallow clones. Travis seems to use a [depth of 50 commits](https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth) by default.
